on:
  push:
    branches: [main, master]

name: Build Site

jobs:
  adodownr:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.0.37

      - name: Install dependencies
        run: |
          sudo apt-get install -y make libcurl4-openssl-dev libssl-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjpeg-dev libpng-dev libtiff-dev libicu-dev pandoc libxml2-dev libgit2-dev libssh2-1-dev zlib1g-dev git

      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}

      - name: Install adodownr
        run: devtools::install_github("lsms-worldbank/adodownr")
        shell: Rscript {0}

      - name: Install here
        run: install.packages("here")
        shell: Rscript {0}

      - name: Build site
        run: adodownr::build_site(pkg_dir = here::here(), site_dir = here::here())
        shell: Rscript {0}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: adodownr
    steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
