on:
  push:
    branches: [main, master]

name: Build Site

jobs:
  adodownr:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.0.37

      - name: Install dependencies
        run: |
          sudo apt-get install -y make
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y libfontconfig1-dev
          sudo apt-get install -y libfreetype6-dev
          sudo apt-get install -y libfribidi-dev
          sudo apt-get install -y libharfbuzz-dev
          sudo apt-get install -y libjpeg-dev
          sudo apt-get install -y libpng-dev
          sudo apt-get install -y libtiff-dev
          sudo apt-get install -y libicu-dev
          sudo apt-get install -y pandoc
          sudo apt-get install -y libxml2-dev
          sudo apt-get install -y libgit2-dev
          sudo apt-get install -y libssh2-1-dev
          sudo apt-get install -y zlib1g-dev
          sudo apt-get install -y git

      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}

      - name: Install adodownr
        run: devtools::install_github("lsms-worldbank/adodownr")
        shell: Rscript {0}

      - name: Install here
        run: install.packages("here")
        shell: Rscript {0}

      - name: Build site
        run: adodownr::build_site(pkg_dir = here::here(), site_dir = here::here())
        shell: Rscript {0}

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '/docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
